/**
 * Phase 3 SKILL.md Generator Tests
 *
 * Test Gates:
 * - skill-md-generation: Verify SKILL.json → SKILL.md generation
 */

import { describe, it, expect } from 'vitest'
import {
  generateSkillMarkdown,
  generateFromJson,
  isMarkdownUpToDate,
  getDefaultContentTemplate,
} from '@opencode/generator'
import { ERROR_CODES } from '@opencode/skill-schema'

describe('skill-md-generation', () => {
  describe('generateSkillMarkdown', () => {
    it('should generate markdown from valid skill data', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: '## What I do\n\nI test things.',
        },
      }

      const result = generateSkillMarkdown(skill)

      expect(result.success).toBe(true)
      expect(result.markdown).toContain('name: Test Skill')
      expect(result.markdown).toContain('description: A test skill')
      expect(result.markdown).toContain('## What I do')
    })

    it('should include frontmatter with required fields', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: 'Content',
        },
      }

      const result = generateSkillMarkdown(skill)

      expect(result.markdown).toContain('---')
      expect(result.markdown).toContain('name: Test Skill')
      expect(result.markdown).toContain('description: A test skill')
    })

    it('should include optional frontmatter fields', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          license: 'MIT',
          compatibility: '>=1.0.0',
          content_md: 'Content',
        },
      }

      const result = generateSkillMarkdown(skill)

      expect(result.markdown).toContain('license: MIT')
      expect(result.markdown).toContain('compatibility: >=1.0.0')
    })

    it('should include generation signature', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: 'Content',
        },
      }

      const result = generateSkillMarkdown(skill)

      expect(result.markdown).toContain('<!-- Generated by OpenCode Skill Generator -->')
      expect(result.markdown).toContain('<!-- Source hash:')
      expect(result.markdown).toContain('<!-- Generated at:')
    })

    it('should use default content when content_md is empty', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: '',
        },
      }

      const result = generateSkillMarkdown(skill)

      expect(result.markdown).toContain('## What I do')
      expect(result.markdown).toContain('## When to use me')
    })

    it('should fail when required fields are missing', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: '',
          description: '',
          content_md: '',
        },
      }

      const result = generateSkillMarkdown(skill)

      expect(result.success).toBe(false)
      expect(result.errors).toContain('Missing required field: skill.name')
      expect(result.errors).toContain('Missing required field: skill.description')
    })
  })

  describe('generateFromJson', () => {
    it('should validate JSON before generating', () => {
      const jsonData = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: 'Content',
        },
        workflow: {
          nodes: [],
          edges: [],
          layout: {},
        },
        policy: {},
      }

      const result = generateFromJson(jsonData)

      expect(result.success).toBe(true)
      expect(result.markdown).toContain('Test Skill')
    })

    it('should return error for invalid JSON', () => {
      const jsonData = {
        // Missing required fields
        version: 'invalid',
      }

      const result = generateFromJson(jsonData)

      expect(result.success).toBe(false)
      expect(result.errors.length).toBeGreaterThan(0)
    })

    it('should return schema_validation_failed error for invalid schema', () => {
      const jsonData = {
        version: 1, // Should be string
      }

      const result = generateFromJson(jsonData)

      expect(result.success).toBe(false)
      expect(result.errors.length).toBeGreaterThan(0)
    })
  })

  describe('isMarkdownUpToDate', () => {
    it('should return true when markdown matches skill data', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: 'Content',
        },
      }

      const generated = generateSkillMarkdown(skill)

      expect(isMarkdownUpToDate(skill, generated.markdown)).toBe(true)
    })

    it('should return false when markdown differs from skill data', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: 'Content',
        },
      }

      const oldMarkdown = `---
name: Old Name
description: Old description
---
`

      expect(isMarkdownUpToDate(skill, oldMarkdown)).toBe(false)
    })

    it('should ignore timestamp when comparing', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Test Skill',
          description: 'A test skill',
          content_md: 'Content',
        },
      }

      const generated = generateSkillMarkdown(skill)
      const withDifferentTimestamp = generated.markdown.replace(
        /<!-- Generated at: .* -->/,
        '<!-- Generated at: 2024-01-01T00:00:00.000Z -->'
      )

      expect(isMarkdownUpToDate(skill, withDifferentTimestamp)).toBe(true)
    })
  })

  describe('getDefaultContentTemplate', () => {
    it('should return default content template', () => {
      const template = getDefaultContentTemplate()

      expect(template).toContain('## What I do')
      expect(template).toContain('## When to use me')
      expect(template).toContain('## How I work')
    })
  })

  describe('skill-md-generation integration', () => {
    it('should generate complete markdown from full skill data', () => {
      const jsonData = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Integration Test Skill',
          description: 'Testing full generation',
          license: 'MIT',
          compatibility: '>=1.0.0',
          metadata: {
            author: 'Test Author',
            tags: ['test', 'integration'],
          },
          content_md: '## What I do\n\nI test integration.',
        },
        workflow: {
          nodes: [
            {
              id: 'n1',
              name: 'Start',
              type: 'Start',
              position: [100, 100],
              config: {},
            },
          ],
          edges: [],
          layout: {
            grid_size: 16,
            snap_to_grid: true,
            viewport: { x: 0, y: 0, zoom: 1 },
          },
        },
        policy: {
          execution_mode: 'sequential',
          failure_mode: 'fail_fast',
        },
      }

      const result = generateFromJson(jsonData)

      expect(result.success).toBe(true)
      expect(result.markdown).toContain('Integration Test Skill')
      expect(result.markdown).toContain('Testing full generation')
      expect(result.markdown).toContain('MIT')
      expect(result.markdown).toContain('## What I do')
      expect(result.markdown).toContain('Generated by OpenCode')
    })

    it('should handle content_md with complex markdown', () => {
      const skill = {
        version: '1',
        skill: {
          id: 'skill-001',
          name: 'Complex Content Skill',
          description: 'Testing complex content',
          content_md: `## What I do

I help with complex tasks.

### Features
- Feature 1
- Feature 2

\`\`\`javascript
// Code example
console.log('Hello');
\`\`\`

## When to use me

Use me for complex workflows.
`,
        },
      }

      const result = generateSkillMarkdown(skill)

      expect(result.success).toBe(true)
      expect(result.markdown).toContain('### Features')
      expect(result.markdown).toContain('- Feature 1')
      expect(result.markdown).toContain('console.log')
    })
  })
})
