/**
 * @opencode/generator
 *
 * SKILL.json → SKILL.md generation pipeline
 * ADR-0007: SKILL.json SoT, SKILL.md is generated artifact
 */

import { createHash } from 'node:crypto'
import { validateSchema } from '@opencode/skill-schema'

// Skill data from SKILL.json
export interface SkillData {
  version: string
  skill: {
    id: string
    name: string
    description: string
    license?: string
    compatibility?: string
    metadata?: Record<string, unknown>
    content_md: string
  }
  workflow?: {
    nodes: unknown[]
    edges: unknown[]
    layout: unknown
  }
  policy?: {
    execution_mode?: string
    failure_mode?: string
  }
}

// Generation result
export interface GenerationResult {
  success: boolean
  markdown: string
  errors: string[]
}

/**
 * Generate frontmatter from skill data
 */
function generateFrontmatter(skill: SkillData['skill']): string {
  const lines: string[] = ['---']

  // Required fields
  lines.push(`name: ${skill.name}`)
  lines.push(`description: ${skill.description}`)

  // Optional fields
  if (skill.license) {
    lines.push(`license: ${skill.license}`)
  }

  if (skill.compatibility) {
    lines.push(`compatibility: ${skill.compatibility}`)
  }

  if (skill.metadata && Object.keys(skill.metadata).length > 0) {
    lines.push(`metadata:`)
    for (const [key, value] of Object.entries(skill.metadata)) {
      lines.push(`  ${key}: ${JSON.stringify(value)}`)
    }
  }

  lines.push('---')
  return lines.join('\n')
}

/**
 * Generate content section from skill content_md
 */
function generateContent(contentMd: string): string {
  if (!contentMd || contentMd.trim().length === 0) {
    return `## What I do

I am a skill that helps you accomplish tasks.

## When to use me

Use me when you need specific assistance with your workflow.
`
  }

  return contentMd
}

/**
 * Calculate hash of skill data for generation signature
 */
function calculateSkillHash(skill: SkillData): string {
  const jsonString = JSON.stringify(skill)
  return createHash('sha256').update(jsonString).digest('hex')
}

/**
 * Generate SKILL.md from SKILL.json data
 * ADR-0007: One-way generation from SKILL.json to SKILL.md
 */
export function generateSkillMarkdown(skill: SkillData): GenerationResult {
  const errors: string[] = []

  // Validate skill data structure
  if (!skill.version) {
    errors.push('Missing required field: version')
  }

  if (!skill.skill?.id) {
    errors.push('Missing required field: skill.id')
  }

  if (!skill.skill?.name) {
    errors.push('Missing required field: skill.name')
  }

  if (!skill.skill?.description) {
    errors.push('Missing required field: skill.description')
  }

  if (errors.length > 0) {
    return {
      success: false,
      markdown: '',
      errors,
    }
  }

  // Generate markdown sections
  const frontmatter = generateFrontmatter(skill.skill)
  const content = generateContent(skill.skill.content_md)

  // Calculate signature
  const hash = calculateSkillHash(skill)
  const timestamp = new Date().toISOString()

  // Combine all sections
  const markdown = `${frontmatter}

${content}

<!-- Generated by OpenCode Skill Generator -->
<!-- Source hash: ${hash} -->
<!-- Generated at: ${timestamp} -->
`

  return {
    success: true,
    markdown,
    errors: [],
  }
}

/**
 * Parse SKILL.json and generate SKILL.md
 */
export function generateFromJson(jsonData: unknown): GenerationResult {
  // First validate the JSON
  const validation = validateSchema(jsonData)

  if (!validation.valid) {
    return {
      success: false,
      markdown: '',
      errors: validation.errors.map(e => `${e.code}: ${e.message_user}`),
    }
  }

  // Cast to skill data and generate
  return generateSkillMarkdown(jsonData as SkillData)
}

/**
 * Check if SKILL.md is up-to-date with SKILL.json
 */
export function isMarkdownUpToDate(skill: SkillData, existingMarkdown: string): boolean {
  const result = generateSkillMarkdown(skill)

  if (!result.success) {
    return false
  }

  // Compare generated markdown with existing (ignoring generation timestamp)
  const existingWithoutTimestamp = existingMarkdown.replace(
    /<!-- Generated at: .* -->/,
    ''
  )
  const generatedWithoutTimestamp = result.markdown.replace(
    /<!-- Generated at: .* -->/,
    ''
  )

  return existingWithoutTimestamp === generatedWithoutTimestamp
}

/**
 * Get default content template for new skills
 */
export function getDefaultContentTemplate(): string {
  return `## What I do

I am a skill that helps you accomplish tasks. Describe what I do here.

## When to use me

Use me when you need specific assistance with your workflow.

## How I work

1. I analyze your request
2. I apply my specialized knowledge
3. I provide you with helpful results
`
}
